# Configuration for Alacritty, the GPU enhanced terminal emulator.

env:
  TERM: xterm-256color

alt_send_esc: false

shell:
  shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - "tmux attach || tmux"

key_bindings:
  - { key: N,         mods: Command,      action: SpawnNewInstance }
  - { key: V,        mods: Control|Shift, action: Paste            }
  - { key: C,        mods: Control|Shift, action: Copy             }
  - { key: Equals,   mods: Control,       action: IncreaseFontSize }
  - { key: Minus,    mods: Control,       action: DecreaseFontSize }
  - { key: PageUp,    mods: Shift,   action: ScrollPageUp,   mode: ~Alt       }
  - { key: PageDown,  mods: Shift,   action: ScrollPageDown, mode: ~Alt       }

window:
  startup_mode: Fullscreen 
  dimensions:
    columns: 0
    lines: 0
  padding:
    x: 4
    y: 0
  dynamic_padding: false
  decorations: none
scrolling:
  history: 300
  multiplier: 3

font:
  normal:
    family: JetBrains Mono
    style: Regular
  size: 20 
  offset:
    x: 2
    y: 0
  glyph_offset:
    x: 0
    y: 0
  # MacOS Only
  use_thin_strokes: true
    
# Colors (Monokai Pro)
colors:
  # Default colors
  primary:
    background: '#2D2A2E'
    foreground: '#FCFCFA'

  # Normal colors
  normal:
    black:   '#403E41'
    red:     '#FF6188'
    green:   '#A9DC76'
    yellow:  '#FFD866'
    blue:    '#FC9867'
    magenta: '#AB9DF2'
    cyan:    '#78DCE8'
    white:   '#FCFCFA'

  # Bright colors
  bright:
    black:   '#727072'
    red:     '#FF6188'
    green:   '#A9DC76'
    yellow:  '#FFD866'
    blue:    '#FC9867'
    magenta: '#AB9DF2'
    cyan:    '#78DCE8'
    white:   '#FCFCFA'

