#!/usr/bin/env zsh

echo "Dotfiles Directory: $DOTFILES"
echo "Stow Folders: $STOW_FOLDERS"

pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
	stow --delete $folder
	stow $folder
done
popd
