#!/bin/zsh
sudo -v

echo "Installing $OSTYPE config"

case "$OSTYPE" in
	darwin*)
		/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
		brew tap Homebrew/bundle
		brew bundle --file="$HOME/.dotfiles/homebrew/Brewfile"
		zsh $HOME/.dotfiles/darwin
	;;
	linux-gnu)
		zsh $HOME/.dotfiles/ubuntu
	;;
esac

