# To make it so Homebrew can handle Brewfiles:
#   `brew tap Homebrew/bundle`
#   `brew bundle --file=~/dotfiles/homebrew/Brewfile`

# Install homebrew packages
brew 'antigen'
brew 'bat'
brew 'git'
brew 'gpg2'
brew 'stow'
brew 'tree'
brew 'tmux'

# install homebrew casks
tap 'homebrew/cask'

cask 'alacritty'
cask 'docker'
cask 'firefox'
cask 'paw'
cask 'visual-studio-code'

# Ruby
# Use [RVM](http://rvm.io/) instead of Homebrew.

# Node
# Use [`nvm`](https://github.com/creationix/nvm) instead of Homebrew.
# Install manually using git clone rather than the install script:
# https://github.com/creationix/nvm#manual-install
